import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <div className="flex items-center gap-2 m-5">
          <Image src="/avatar.gif" alt="avatar" height={45} width={45} className="rounded-full" />

          <p className="text-2xl text-white">Bluzzi</p>
        </div>
      </header>
    </div>
  );
};

export default Home;
