import type { Skill } from "./skill.type";

export const skills: Skill[] = [
  { title: "NodeJS", logo: "/skills/nodejs.svg", link: "https://nodejs.org" },
  { title: "TypeScript", logo: "/skills/typescript.svg", link: "https://www.typescriptlang.org" },
  { title: "Pnpm", logo: "/skills/pnpm.svg", link: "https://pnpm.io" },
  { title: "React", logo: "/skills/react.svg", link: "https://react.dev" },
  { title: "Vite", logo: "/skills/vite.svg", link: "https://vite.dev" },
  { title: "React Router", logo: "/skills/react-router.svg", link: "https://reactrouter.com" },
  { title: "TanStack", logo: "/skills/tanstack.png", link: "https://tanstack.com" },
  { title: "Shadcn", logo: "/skills/shadcn.svg", link: "https://ui.shadcn.com" },
  { title: "Tailwind", logo: "/skills/tailwind.svg", link: "https://tailwindcss.com" },
  { title: "Fastify", logo: "/skills/fastify.svg", link: "https://fastify.dev" },
  { title: "Drizzle", logo: "/skills/drizzle.svg", link: "https://orm.drizzle.team" },
  { title: "Zod", logo: "/skills/zod.png", link: "https://zod.dev" },
  { title: "PostgreSQL", logo: "/skills/postgresql.svg", link: "https://www.postgresql.org" },
  { title: "Redis", logo: "/skills/redis.svg", link: "https://redis.io" },
  { title: "Playwright", logo: "/skills/playwright.svg", link: "https://playwright.dev" },
  { title: "ESLint", logo: "/skills/eslint.svg", link: "https://eslint.org" },
  { title: "Railway", logo: "/skills/railway.svg", link: "https://railway.app" },
  { title: "VSCode", logo: "/skills/vscode.svg", link: "https://code.visualstudio.com" },
  { title: "Notion", logo: "/skills/notion.svg", link: "https://www.notion.so" },
  // { title: "Google Cloud", logo: "/skills/google-cloud.svg", link: "https://cloud.google.com" },
  // { title: "RabbitMQ", logo: "/skills/rabbitmq.svg", link: "https://www.rabbitmq.com" },
  // { title: "Next", logo: "/skills/next-js.svg", link: "https://nextjs.org" },
  // { title: "Vitest", logo: "/skills/vitest.svg", link: "https://vitest.dev" },
  // { title: "Meilisearch", logo: "/skills/meilisearch.svg", link: "https://www.meilisearch.com" },
  // { title: "CSS", logo: "/skills/css.png", link: "https://github.com/css-modules/css-modules },
  // { title: "SASS", logo: "/skills/sass.png", link: "https://sass-lang.com" },
  // { title: "Redux", logo: "/skills/redux.webp", link: "https://redux.js.org" },
  // { title: "Vanilla Extract", logo: "/skills/vanilla-extract.svg", link: "https://vanilla-extract.style" },
  // { title: "Mantine", logo: "/skills/mantine.svg", link: "https://mantine.dev" },
  // { title: "NextUI", logo: "/skills/next-ui.svg", link: "https://nextui.org" },
  // { title: "Radix", logo: "/skills/radix.svg", link: "https://www.radix-ui.com" },
  // { title: "Zustand", logo: "/skills/zustand.png", link: "https://zustand-demo.pmnd.rs" },
  // { title: "Testing Library", logo: "/skills/testing-library.png", link: "https://testing-library.com" },
  // { title: "Storybook", logo: "/skills/storybook.png", link: "https://storybook.js.org" },
  // { title: "TanStack Query", logo: "/skills/tanstack-query.png", link: "https://tanstack.com/query/v4" },
  // { title: "React Hook Form", logo: "/skills/react-hook-form.svg", link: "https://react-hook-form.com" },
  // { title: "React Email", logo: "/skills/react-email.svg", link: "https://react.email" },
  // { title: "DayJS", logo: "/skills/dayjs-emoji.png", link: "https://day.js.org" },
  // { title: "GitHub Actions", logo: "/skills/github-actions.svg", link: "https://github.com/features/actions" },
  // { title: "GraphQL", logo: "/skills/graphql.png", link: "https://graphql.org" },
  // { title: "PowerShell", logo: "/skills/powershell.svg", link: "https://learn.microsoft.com/en-us/powershell" },
  // { title: "Faker", logo: "/skills/faker.svg", link: "https://fakerjs.dev" },
  // { title: "Prisma", logo: "/skills/prisma.svg", link: "https://www.prisma.io" },
];
