name: Build
on: push
  
jobs:
  eslint:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses:  actions/setup-node@v3
      - name: Code checkout
        uses: actions/checkout@v2
      - name: Install deps
        run: npm install
      - name: Build Next
        run: npm run build
