name: Tests

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
      - run: npm install
      - name: Run ESLint
        run: npm run lint
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v3
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run typecheck
        run: npx tsc -b .
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v3
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run Vitest
        run: npm run test:unit
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v3
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build