name: Unit test
on: pull_request

env:
  NODE_VERSION: 18
  
jobs:
  eslint:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses:  actions/setup-node@v2
        with: 
          node-version: ${{ env.NODE_VERSION }}
      - name: Code checkout
        uses: actions/checkout@v2
      - name: Install deps
        run: npm install
      - name: Run Vitest
        run: npm run test:unit
